### ISSUE TITLE
Review and Rework FCM Frontend

### ISSUE THREAD

**Issue by FabiApfelkern** [policycompass/policycompass#199]
I think the entire FCM frontend is to complex and complicated. Honestly I have no clue what I can do there and how. You should rethink the layout I do some mockups and we can discuss it here. Some of my ideas are:
 - Make it a wizard like dataset upload to guide user through the steps
 - A lot of help texts for each button
- Why is the edit button called "Run Simulation"
- What does the green and red color of the concepts mean

**Comment by FabiApfelkern** [comment]
@aquinas9 This really needs some attention in Sprint 5. @YuriGlickman Can you male concrete suggestions?

**Comment by YuriGlickman** [comment]
Ok. I will do it.

**Comment by aquinas9** [comment]
◦Why is the edit button called "Run Simulation" : This was the recommendation from CCC meeting...If anyone have any idea, feel free to let us know.
◦What does the green and red color of the concepts mean: This was also request from other partners. When user clicks one concept, the color of in & out conept to selected concept changed so that user can easily recognize the in and out linkage among them.

**Comment by FabiApfelkern** [comment]
@belalakbar Why is this closed. The FCM Frontend looks the same.
