### ISSUE TITLE
Faceted search

### ISSUE THREAD

**Issue by YuriGlickman** [policycompass/policycompass#203]
The implementation of facented search have to be included in the second release of the platform and be ready by the sprint 5 latest.

At the moment  we have only a mock-up. I think the faceted search should have at least the following sections:
Content type - called "Output" now
Category - list of 13 data domains 
Location - with a list of countries
Time period

**Comment by cbotsikas** [comment]
Thank you for your input @YuriGlickman. I'm closing this as it's duplicate to https://github.com/policycompass/policycompass/issues/138

**Comment by YuriGlickman** [comment]
Hi Christos,
So, the categories are:
Content type - called "Output" now
Category - list of 13 data domains
Location - with a list of countries.
Time period

**Comment by cbotsikas** [comment]
@YuriGlickman adding policy domains in facet can get messy due to limited space. take a look here:
![capture](https://cloud.githubusercontent.com/assets/1640100/10938578/b2baabc2-82fb-11e5-965c-dd01aac0f1a6.PNG)
About the "Location - with a list of countries" where do we use such info?

**Comment by FabiApfelkern** [comment]
We decided on Policy Domains and Location instead of Category and Language.  
Furthermore to change to "real" faceted search.

**Comment by YuriGlickman** [comment]
Hi Christos,

I do not know if the currently deployed version on stage is up to date. If yes, can you please make lenght of strings in facets event smaller, so the domain names would not clash with the number of elements. I keep the ticket closed since it is a minor change.

**Comment by cbotsikas** [comment]
@YuriGlickman It's up to date. I'm not quite sure what you have in mind, so i've prepared the following change options so that we can decide.

1) smaller fonts
![image](https://cloud.githubusercontent.com/assets/1640100/11568588/53cf1838-99ed-11e5-90fd-78e39ef15cb5.png)

2) a bigger gap between the label and the number of elements
![image](https://cloud.githubusercontent.com/assets/1640100/11568597/64ee9f62-99ed-11e5-9f08-4b31ddd25bc0.png)

3) bigger facet boxes
![image](https://cloud.githubusercontent.com/assets/1640100/11568825/ad13bd58-99ee-11e5-9493-73808e9647c3.png)

4) normal text for facets (removed bold)
![image](https://cloud.githubusercontent.com/assets/1640100/11568864/e4aee1f2-99ee-11e5-9ccc-2d3571bc5356.png)

**Comment by cbotsikas** [comment]
I think the smaller font option (1) is making the text hard to read

**Comment by YuriGlickman** [comment]
Hi Christos,
Maybe the issue is only by me because I have magnified fonts... So, it looks like on a screenshot below:

![facet](https://cloud.githubusercontent.com/assets/8254248/11589845/0b8b53d0-9a8c-11e5-8db5-717b3f215ab8.jpg)

I think the Option 2 could help in my case.

**Comment by cbotsikas** [comment]
@YuriGlickman It's a bug related to the browser's implementation of the text-overflow :/ I've created a new issue.

**Comment by cbotsikas** [comment]
https://github.com/policycompass/policycompass/issues/394
