### ISSUE TITLE
Upgrade angular to 1.4

### ISSUE THREAD

**Issue by nidico** [policycompass/policycompass#212]
We're still using the outdated Angular 1.2. Angular 1.3 and 1.4 have a couple of nice features which we might want to use.

There shouldn't be too much incompatible changes, but we need to test well when doing this.

Of course, other dependencies could also be updated, but this issue is about angular.

**Comment by FabiApfelkern** [comment]
I also would like to have this migration. But I'm not sure if it is a good idea now. I was thinking to do all those migrations after the review. The backend needs a lot of updates as well. Because for me it not clear how much effort it is. We have to migrate the dependencies in some cases and have to test every bit of it. What do you think? And I'm curious, what particular features do you mean?

**Comment by FabiApfelkern** [comment]
@nidico Do we do something about it in this Sprint or just leave it for later?

**Comment by nidico** [comment]
Leave it for whenever someone finds the time. Probably not in this sprint.

> And I'm curious, what particular features do you mean?

Yesterday, I wanted to use `$watchGroup`.
