### ISSUE TITLE
Continuous Integration (Test + Deploy)

### ISSUE THREAD

**Issue by nidico** [policycompass/policycompass#23]
Requirements:

- run the testsuite
- send emails if broken
- update test server if successful

Tasks:

- [x] "rebuild" script - LIQD
- [x] Automatic build (.travis.yml) - LIQD
- [x] Trigger rebuild on dev-server - coordinate with FOKUS data center

**Comment by slomo** [comment]
@nidico can you further specify the rebuild script? Is this related to #22

**Comment by nidico** [comment]
Yes, that's what it's about.

**Comment by FabiApfelkern** [comment]
@nidico @slomo Is it possible to get this within Sprint 1? At least a possibility to update everything with the Makefile. I think it is not suitable at the moment.

**Comment by FabiApfelkern** [comment]
@cbotsikas We have talked about this. Any progress? Do we/you manage in Sprint 7?

**Comment by nidico** [comment]
@FabiApfelkern are you in the right issue? About this one, I'd say no, move to year 3.

**Comment by FabiApfelkern** [comment]
I chatted a little bit with @cbotsikas about it and he thought it is possible to have it. @cbotsikas What do you say?

**Comment by slomo** [comment]
So currently we have a running travis integration. We can add a ssh key to the stage server policycompass user and trigger the Makefile from travis after a successful build.

**Comment by slomo** [comment]
Should the build be triggered on the policycompass/policycompass repository? Or directly on policycompass/policycompass-services and policycompass/policycompass-frontend?

The first case would be easier, than the latter one.

**Comment by cbotsikas** [comment]
AFAIK, policycompass's submodules have nothing to do with the version that is being deployed since the makefile always pulls the latest version. This is why the submodule versions are 8 months outdated.
Currently  policycompass/policycompass repository is not updated that often and if we force the build trigger through that repo, it would add an unnecessary overhead. 
What was the current solution for stage? It used to work, for sure 2 months ago, when something was merged on policycompass-services or policycompass-frontend...
