### ISSUE TITLE
"Simulation results" and "graph" tab

### ISSUE THREAD

**Issue by YuriGlickman** [policycompass/policycompass#251]
It is difficult to understand how simulation works. We should aim to make the tools integrated in Policy Compass to be understandable for general users. We do not need to explain all details, but they should understand the meaning of the numbers or curves which they see.  I propose the following:
1) Add an explanational text for the simulation results and put it under a question mark, like it is done for the dataset upload: https://frontend-stage.policycompass.eu/app/#!/datasets/create 
![question mark](https://cloud.githubusercontent.com/assets/8254248/9920177/258b7262-5cd2-11e5-8196-f170a554aee7.jpg)

2) In simulation results and in the graph  you show results always for 20 steps. Are they all important? If only some of them are meaningful, please do not show other. 

3) Provide explanation for the Impact analyses at the Impact analyses tabs. Put your text under the question mark.

**Comment by YuriGlickman** [comment]
2) In simulation results and in the graph you show results always for 20 steps. Are they all important? If only some of them are meaningful, please do not show other. 
3) Provide explanation for the Impact analyses at the Impact analyses tabs. Put your text under the question mark.

**Comment by cbotsikas** [comment]
@belalakbar you can't close issues without resolving them; either by replying with detailed solution or linking to merged commits and/or new issues

**Comment by belalakbar** [comment]
merged commit 912bb50  by fabian on 7 days ago.

**Comment by FabiApfelkern** [comment]
@belalakbar The commit links should be clickable. Just copy the entire URL

**Comment by cbotsikas** [comment]
@belalakbar I had to search for the [912bb50](https://github.com/policycompass/policycompass-frontend/commit/912bb503c0096bf9018dcaf19dc29acbb311c96b) (please, as @FabiApfelkern said, use full urls next time) which apparently merges PR https://github.com/policycompass/policycompass-frontend/pull/218 that solves Issue https://github.com/policycompass/policycompass/issues/268 and in this case, it's only the 1st point.

What about the 2nd and 3nd point? I think the 2nd one is also related with Issue https://github.com/policycompass/policycompass/issues/348

**Comment by belalakbar** [comment]
2nd point 
The 20 number of iteration are important because based on experiment we have observed that all the concept get the convergence within 20 iteration. it also shows that the concept does not change the convergence vale again. 
for example after  5 iteration concept converge up to 8th iteration but it again converge from 8th to 15th. therefore we have twenty iteration that we can have the fixed values of concept after optimal number of iteration. 
The important value is last value to see the final impact and the number of iteration are also important.

3rd point is already done 
 
![help menu with impact](https://cloud.githubusercontent.com/assets/12219711/11036394/3b11bad6-86f0-11e5-91e9-e98f379cc0fd.png)

**Comment by belalakbar** [comment]
@cbotsikas 
can I close this and question 348 now?
