### ISSUE TITLE
Disable zoom of FCM graph through scroll

### ISSUE THREAD

**Issue by nidico** [policycompass/policycompass#288]
Using the mouse scroll wheel should be reserved for page scrolling. Zooming the FCM graph through scrolling should be prevented.

**Comment by cbotsikas** [comment]
I think scrolling is captured properly. It's zooming only when the cursor is on the FCM. If your cursor is outside the FCM, the page is scrolling.

Do you have a different behavior?  

I'm on Windows with Chrome Version 45.0.2454.101 m (64-bit) ATM.

**Comment by nidico** [comment]
> I think scrolling is captured properly. It's zooming only when the cursor is on the FCM.

Even then, it's pretty annoying, as the cursor ends up on top of the FCM graph during scrolling...

**Comment by cbotsikas** [comment]
it's essentially the same way the visualization is working when using maps like: https://frontend-stage.policycompass.eu/app/#!/visualizations/12

If it's still an issue, i wouldn't remove the functionality but instead add a keyboard combo like (Ctrl+scrolling)

**Comment by aquinas9** [comment]
I think we can close this issues.

**Comment by cbotsikas** [comment]
@aquinas9 with what resolution?

**Comment by aquinas9** [comment]
@cbotsikas @belalakbar 
I don't know exactly what is the difference of scroll action in FCM and visualisation. 
Can you clear what function we need to implement more for Bilal and me?

**Comment by cbotsikas** [comment]
Visualization has scroll to zoom functionality disabled by default and provides a checkbox to enable it. 
in FCM if the mouse cursor in on top of the FCM map, it captures the scroll action to zoom in/out.
For me, the current situation is fine.
If @nidico or others still find this behavior annoying, you could either implement a checkbox, similar to visualization, that enables and disables zoom functionality or wrap the scroll handler with a keyboard combination check; if a key is pressed (eg. SHIFT key) prevent the default scroll action and zoom the FCM map.

**Comment by cbotsikas** [comment]
talking about the map's zoom reminded me an other question/issue. Is the zoom level saved with the elements' position information? If yes, i think you need to save the FCM's size too (width & height) so that you can use that information and scale the positions and zoom level accordingly. for example in this FCM: https://alpha.policycompass.eu/app/#!/models/11 this is what i see:
![capture](https://cloud.githubusercontent.com/assets/1640100/11425527/dfe91758-9455-11e5-96ae-7e11e3040ad9.PNG)
Of course i can click the button above the zoom control and fix the diagram to fit my screen but if i try the same button in https://alpha.policycompass.eu/app/#!/models/1, the diagram is unreadable. 
Are you planning to have an auto rearrange functionality, similar to [this one](http://gojs.net/latest/samples/interactiveForce.html)?
I'm also asking because at the moment for the share images i generate i use the functionality to fit the graph in the screen.

**Comment by cbotsikas** [comment]
I'm reopening till a final decision or fix is made.

**Comment by nidico** [comment]
IIRC I opened this issue during / after a telco some weeks ago. During that telco we said that the current behavior is broken and should be changed (e.g. by disabling scroll to zoom by default). This is also and still my opinion.

During the review I've seen multiple persons scrolling the page, ending up with the cursor on top of the graph, trying to go on scrolling, but zoom instead.

Looking at it from a different angle I'd question whether zooming is practically *that* relevant. If FCMs are that big that zooming is really relevant, they're probably too big for policy compass.

**Comment by FabiApfelkern** [comment]
I think it is general a good idea to interact with the graph via mouse, but there HAS to be an indication that the mouse is in a different mode when hovering the FCM canvas. E.g. the mouse cursor is changing.
