### ISSUE TITLE
Delete dataset

### ISSUE THREAD

**Issue by nadiapo** [policycompass/policycompass#334]
I can delete a dataset even if there is content created based on that dataset. For example I have a visualisation based on a dataset which I deleted which now displays an error
{"detail":"Not found"}

**Comment by cbotsikas** [comment]
@nadiapo I'm afraid that's the case for every entity in PC since almost everything is loosely linked together. Visualizations contain datasets and events, datasets are linked with indicators, metrics use indicators, FCM links to datasets etc. 
Maybe we should consider the option that "deleting a entity", doesn't actually delete it (cause in that case we brake the linked entities) but instead flag it as "non usable for future use" aka, keep it in the system, as long as it's used elsewhere, and hide it from search and select boxes.
Another option is to change the (loosely) linking-by-id to direct-copy all relative data on the target's entity model, so as not to be affected by changes or deletions of the origin entity. (imagine the case where i've created a visualization using an event and then the owner of that event changes the event data entirely)
@YuriGlickman @nidico any thoughts?

**Comment by nidico** [comment]
> I'm afraid that's the case for every entity in PC since almost everything is loosely linked together

Yes, no referential integrity assured.

> Maybe we should consider the option that "deleting a entity", doesn't actually delete it (cause in that case we brake the linked entities) but instead flag it as "non usable for future use" aka, keep it in the system, as long as it's used elsewhere, and hide it from search and select boxes.

I like that idea.

**Comment by FabiApfelkern** [comment]
This is a difficult topic. We should postpone to after the review.
