### ISSUE TITLE
FCM simulation and graphs should be available in view mode

### ISSUE THREAD

**Issue by cbotsikas** [policycompass/policycompass#344]

**Comment by belalakbar** [comment]
What does mean by view mode?

**Comment by cbotsikas** [comment]
When viewing a Causal Model for example here: https://alpha.policycompass.eu/app/#!/models/9
There are two tabs below the graph labeled "Simulation" and "Graph" that contain data only when someone is in Edit Mode (aka: https://alpha.policycompass.eu/app/#!/models/9/edit)

**Comment by aquinas9** [comment]
One of my concern for this issue is that we don't save all the simulation result and only simulation parameters used for recent simulation are saved to db table. I think there are two option for this.

If you think the previous simulation results should be shown before going into edit mode,  firstly we need to consider how much storage is expected till the future  and then create new tables for this. 

But If think we can simply hide this two tab in showing mode. Saving all simulation results for this might be not needed. How do you guys feel abut this?

**Comment by FabiApfelkern** [comment]
@aquinas9 Couldn't you just run the simulation like you do it in the edit mode? I don't get the issue here.

**Comment by belalakbar** [comment]
https://github.com/policycompass/policycompass-frontend/pull/265

**Comment by FabiApfelkern** [comment]
@mohammedbahja Do you want to move this to Sprint 9?

**Comment by mohammedbahja** [comment]
Yes, I have moved it.

**Comment by mohammedbahja** [comment]
policycompass/policycompass/issues/638
