### ISSUE TITLE
Casual Models Creation

### ISSUE THREAD

**Issue by cbotsikas** [policycompass/policycompass#348]
* The number of iterations seems to be fixed at 20 iterations, thus not allowing the user to understand at which iteration the values stabilize (the concept values corresponding to iterations after convergence are unnecessary information)
* The fixed concept/weight values are reasonable, but fixed values for calculations at the iteration level do not allow for subtle variations to be evident
* Testing of the Causal Model component is difficult, unless the ‘advanced settings’ (activator and scale) are explained and more decimal digits are used.

**Comment by belalakbar** [comment]
@cbotsikas 
* Yes iteration are fixed at 20, because each concept has a convergence value at different number of iteration. IN FCM theory the policy maker (user) need to observe the constant value rather number iteration. therefore,   initially the number of iteration was 50, however  in different run simulation result we (brunel team) observe that within the 20 iteration each concept get the constant state so the number of iteration are fixed at 20.

* in FCM causal model fixed concept is that which do have input from other concepts. in initial causal model the fixed concept is selected by the user , however now new algorithm automatically detect the concept without input from other concept and keep its values fixed through the iterations. 
* the actual outcome of the FCM simulation is number between 0 and 1, however this number is converted into the fuzzy values similar to initial concept values so the user can know the outcome in fuzzy terms. However if the values are not converted into fuzzy value then you can see the difference in digital point.

**Comment by takiant** [comment]
@belalakbar 
1) So, is it possible to present only the number of iterations until convergence? (which may be well below 20)

2) What we mean is that if a concept's assigned initial value is 0.2 and the final value after the simulation is e.g. 0.3, which is the final value that the user will get? 0.2 or 0.4? Additionally, should we add more decimal digits to show even small variations in a concept's value?

3) Please explain the 'advanced settings' choices in the platform (e.g. include tooltips)

**Comment by belalakbar** [comment]
I think I s not possible to present the number of iterations until convergence because each concept have different number of iterations until convergence , however model run given iteration. 
The user will use the final value 0.4. 
I will add more description about advance setting in help menu.

**Comment by belalakbar** [comment]
reference to https://github.com/policycompass/policycompass/issues/368

**Comment by belalakbar** [comment]
policycompass/policycompass-fcmmanager#21
