### ISSUE TITLE
Error Popup when Editing a FCM

### ISSUE THREAD

**Issue by FabiApfelkern** [policycompass/policycompass#355]
When editing a FCM a error popup with the message "datasetList.results[j] is undefined" appears.

**Comment by belalakbar** [comment]
Hi @FabiApfelkern and @mmilaprat 

Regarding this error, I am not facing this error on my local machine. I investigated this error further and I think the following is may be the issue:

Find below the error position:

  $scope.Datasets = Datasets.query({}, function(datasetList) 
  {
	for (i=0; i<$scope.SimulationConcepts.length; i++)
	{
		for (j=0; j<datasetList.count; j++)
		{
			if (datasetList.results[j].id==$scope.SimulationConcepts[i].metricId) 
Note: Generate Error is related to Dataset id. Can you check the value of Dataset.count properties and total number of actual Datasets are equal on the live server or not.
Please tell me how can I access the api directly on stage server to see the datasets List.
			{
				$scope.SimulationConcepts[i].metricTitle = datasetList.results[j].title;
			}
		}
	}

  },
  function(error) {
    throw { message: JSON.stringify(error.data)};
  });

**Comment by cbotsikas** [comment]
The issue can be seen here:
https://frontend-stage.policycompass.eu/app/#!/models/9/edit
https://frontend-stage.policycompass.eu/app/#!/models/4/edit
don't know about others

**Comment by cbotsikas** [comment]
you can't reproduce the error on your local machine because you probably don't have more that 10 datasets. datasetList.count is the total number of datasets which may not be equal to datasetList.results.length. You could ask for more results in one request by passing page_size parameter on the request, but i don't recommend it. 

Based on the following i think you're doing things wrong. 
```
if (datasetList.results[j].id==$scope.SimulationConcepts[i].metricId)
{
     $scope.SimulationConcepts[i].metricTitle = datasetList.results[j].title;
}
```

First of all, you have two asynchronous request executed in parallel and on the second one you use an array populated when the first call is done. So basically you're hopping that the 2nd one will execute last which is not guaranteed. 

Second, you shouldn't fetch all datasets in order to get the title of individual ones. You can simply ask for them like this:
```
Dataset.get({id: SimulationConcept.metricId}, function (dataset){
    SimulationConcept.metric=dataset.title;
});
```

**Comment by cbotsikas** [comment]
@FabiApfelkern just to make sure, the error is actually "Cannot read property 'id' of undefined" and in the console there is the error saying "TypeError: Cannot read property 'id' of undefined
    ***at cytoscape.js:242***" correct?

**Comment by FabiApfelkern** [comment]
No it is excatly: "angular.min.js (line 92) Error: datasetList.results[j] is undefined"

**Comment by cbotsikas** [comment]
ok, it's the same error, different browser...

**Comment by belalakbar** [comment]
https://github.com/policycompass/policycompass-frontend/pull/227

**Comment by cbotsikas** [comment]
@belalakbar although the error has disappeared, the actual code lines [236-245](https://github.com/policycompass/policycompass-frontend/blob/master/app/modules/fcm/controllers/cytoscape.js#L236-L245) are never executed because $scope.SimulationConcepts.length is always 0 by the time it's executed. You need to move that, most likely inside the loop you have already at lines [214-221](https://github.com/policycompass/policycompass-frontend/blob/master/app/modules/fcm/controllers/cytoscape.js#L214-L221). I don't understand what you try to do but i'm guessing it's the correct place to put that code, since the loop is the same and the $scope.SimulationConcepts is populated there.

**Comment by belalakbar** [comment]
i will look into it.
