### ISSUE TITLE
Auto Save FCM Before Running Simulation

### ISSUE THREAD

**Issue by FabiApfelkern** [policycompass/policycompass#359]
At the moment it is necessary to save a FCM before changes apply, This confuses and is not clear for the user. He executes a simulation and nothing changes.

**Comment by belalakbar** [comment]
@FabiApfelkern the changes in FCM saved at two different points. 1st when some make changes in the causal model. it need to be saved  before changes in the value section. however as the user change the values of concept and weight in the simulation section these changes already automatically saved.

**Comment by FabiApfelkern** [comment]
I couldn't follow you explanations 100%. Have you changed something or just stated a fact?

**Comment by belalakbar** [comment]
i have stated a fact that 
model editing and run simulation are two different level so need to dealt at different level. 

level one is model editing (which add concept and creating association), which need to be save before going to simulations level. 
at simulation level the concept values and weights are edited when user hit the run simulation tab it automatically save the concept values and weight input. 

FACT is it is been detail discussed in burn team & YURI already that editing causal model and run simulation is different. so need to be separated. 

because before the concept values are part of editing which later removed from add concept (causal  model editing level) and  brought to simulation level so the user can change different values can run the simulation. 


my concluding point is 
the changes made in causal model (add concept or delete, create association)  need to saved by user before running simulation tab. 
however the changes made in run simulation tab do not required to be saved will automatically saved and reflect in results.

that is layout and process for developing and running the FCM as also described help section.

**Comment by belalakbar** [comment]
@FabiApfelkern 
to make it more clear for user I will more explanation in the help menu.
second 
I will make pop up message " user need to save the causal model before running the simulation" as he hit the RUN simulation tab without saving the model. 

it will make more clear to user.

**Comment by FabiApfelkern** [comment]
Thank you for the explanations. Probably it is just a misunderstanding. Yuri and me had just another look. We didn't know that you already save the changes when running a simulation. So actually the used did not need to save before. But the issue is that the lower menu "Relationships" is not in sync with the graphical view of the model. So when you change the weight in the lower menu it is nor reflected in the graphic. When you click "Run Simulation" is is updated, but on the context menu of the association it is still the old one. So summarized we think we need the following things:
- Always keep graphic and simulation menu in sync
- Clearly inform the user when what is saved

**Comment by aquinas9** [comment]
@FabiApfelkern 

I know the situation is quite complex :) 

The reason we haven't synchronise the graph and simulation menu in lower section is coming from what we need to save. Basically, when user browse the saved model, the valued are coming from last simulation action. 
To revise the FCM graph, user need to work with the graphical menu within canvas and save the changes. Or user run the simulation with different parameter setting, the changed values will be saved and appear in the graph. 

We will clearly mention about the details in help menu.

**Comment by belalakbar** [comment]
https://github.com/policycompass/policycompass-frontend/pull/234
