### ISSUE TITLE
Charts legend should be improved

### ISSUE THREAD

**Issue by YuriGlickman** [policycompass/policycompass#402]
The Chart legend has to be improved. Sometimes we still see ID instead of the dataset acronym, like here:
https://alpha.policycompass.eu/app/#!/visualizations/create/?datasets=115

But in general,we need to do something with the legends of visualisations. From the legend it should be clear which line belongs to which indicator and to which data dimension (country).

Maybe try to put the legends in two lines...

**Comment by mmilaprat** [comment]
In two lines is difficult because we can have n lines of legends.

At this moment we add the dataset acronym to the individual legend between square brackets "[]" to be able to distinguish each one if the visualisation has n lines with the same legend (example 2 legends of the same country, this is possible if we link 2 datasets that has the same country). When the legend is plotted, we cut the length of it if it is too large.

The full name of the is displayed into the tooltip that appears onmouse over the legend.

![04-01-2016 15-10-07](https://cloud.githubusercontent.com/assets/6602727/12091407/32995f34-b2f7-11e5-9dbf-1aec27510ba3.jpg)


A posible solution is just to add the acronym when we have more than one dataset linked with a visualisation, but we need to cut labels to try to get a correct legend.

**Comment by YuriGlickman** [comment]
I like the tooltip. I propose to put the text  "Click over to hide" on the next line after the name and make it italic.

At the moment the tooltip works only for saved visualisation. If you add it for the non-saved visualisations then it solved the issue.

**Comment by mmilaprat** [comment]
If you cick over the legends in edit mode the modal window that enable you to configure datasets is opened. 

If we add the toolip in edit, we must remove the text "click over". "Click over" only appears in view mode.

**Comment by YuriGlickman** [comment]
yes, can you remove this text for the edit mode and add the tooltip?`I think the tooltip is even more useful in the edit mode...

**Comment by mmilaprat** [comment]
yes
