### ISSUE TITLE
Datasets sometimes not loading

### ISSUE THREAD

**Issue by FabiApfelkern** [policycompass/policycompass#430]
CCC and I have it also sometimes, that the datasets are just not loaded at the loading indicator stays forever. 

![screenshot from 2016-01-22 11-32-20](https://cloud.githubusercontent.com/assets/1488424/12508364/d1f17708-c0fb-11e5-8d70-309afbc63095.png)

**Comment by mmilaprat** [comment]
Have you found some casuistic that can help me to replicate this issue?

**Comment by FabiApfelkern** [comment]
@mmilaprat Sorry I have no idea how to force that behavior. Did you never have it?

**Comment by mmilaprat** [comment]
I was not aware of this error, but I belive you

**Comment by mmilaprat** [comment]
Can you check if it happens with the latest updates of the visualisation?

**Comment by mmilaprat** [comment]
Do you have any suggestion about how I can replicate this problem? I tried with chrome with different network configuration, with different real WIFI connections and I cannot get this error.

**Comment by YuriGlickman** [comment]
I just repeated the problem with Firefox. In my case I see the message "No individuals are found". To repeat the bug: take any dataset, press visualise and then configure datasets:
![bug](https://cloud.githubusercontent.com/assets/8254248/13566508/36d15558-e456-11e5-8b66-c66e4df3643b.jpg)

**Comment by YuriGlickman** [comment]
In Chrome I cannot repeat it...

**Comment by cbotsikas** [comment]
For me it works fine in both Chrome and Firefox.
Try reproducing it again but this time open the Network console (Ctrl+Shift+Q), reload the page to enable traffic capturing, reproduce the error, right click on any entry in the Network console, Save all as HAR and send the file privately, so that i can investigate further.
![untitled](https://cloud.githubusercontent.com/assets/1640100/13566949/63dc1be4-e458-11e5-8ec8-e26f09fb9ea6.png)

**Comment by cbotsikas** [comment]
The above instructions are for Firefox

**Comment by YuriGlickman** [comment]
I cannot repeat it with the activated console. The bug can be seen only if you click quickly: so you jump to the next page before the scripts at the previous have been completely loaded. I think it happens when you press "Configure Datasets" before all visualisatio scripts have been loaded. If I then close the pop-up and activate the console then press "Configure Datasets" then I see that:
![bug2](https://cloud.githubusercontent.com/assets/8254248/13567956/9e70ec52-e45e-11e5-8736-a669de75144b.jpg)
But if I reload (by F5) then the issue is gone.

**Comment by th0br0** [comment]
The 'no indivduals found' error can be reproduced by opening up the dataset configuration window, removing the dataset, confirming the deletion, then   canceling, and then reopening the configure dataset wizard. Probably needs filing as a separate bug.

Just reading the code,

[the logic here can't work. the if will always fire. what is the intention?](https://github.com/policycompass/policycompass-frontend/blob/842ed911bcf24aa4eb1f3c8f2ab69cf8300654d6/app/modules/visualization/controllers/visualizationControllers.js#L137)

the logic for showing / hiding the "loading" seems to be wrapped up in a promise handler. Any errors caused during the attempted resolution of the promise will fail silently (without any console output) - this might be a potential source of the issue. A simple wait timeout would be useful here as well. 

There exists another likely (I don't fully grok what you're trying to do) logic error inside the promise success handler itself.

The if-clause [here](https://github.com/policycompass/policycompass-frontend/blob/842ed911bcf24aa4eb1f3c8f2ab69cf8300654d6/app/modules/visualization/controllers/visualizationControllers.js#L194) could be refactored to:

```js
$scope.IndividualDatasetCheckboxes_[containerIndex] = 
    $scope.IndividualDatasetCheckboxes_[containerIndex] || [];

$scope.IndividualDatasetCheckboxes_[containerIndex].push($arrayValores['id']);
$scope.ModalIndividualDatasetCheckboxes_[containerIndex] = 
    $scope.IndividualDatasetCheckboxes_[containerIndex];

// The follow if-clause is what can prevent the loading dialog from resolving:
// arrayIndividualListDataset can be empty, therefore having length 0.
// however, the former(TMP2), now any of the checkboxes arrays above, has at least length 1 due to the non-conditional push. Therefore, the below if might never fire - preventing the loading spinner from being hidden.
/*
if(arrayIndividualListDataset.length==$scope.ModalIndividualDatasetCheckboxes_[containerIndex].length) {
	$scope.showListIndividuals[containerIndex] = true;
}
*/
// I've removed the if-clause here. We should much rather throw an error in the promise and then catch that in a failure handler than failing silently. 
$scope.showListIndividuals[containerIndex] = true;

```

**Comment by cbotsikas** [comment]
@th0br0 although you are correct about the code quality, i don't think the issue is related with any of the above mentioned code issues. Also, the reproduction method, is visually the same but not the same issue. @mmilaprat you should address that too.

Now, about the issue, the only way i could reproduce this, was by placing a brakepoint [at line 194](https://github.com/policycompass/policycompass-frontend/blob/842ed911bcf24aa4eb1f3c8f2ab69cf8300654d6/app/modules/visualization/controllers/visualizationControllers.js#L194) and then manually clearing the individualCombo_value_ array ([visualizing dataset 59](https://alpha.policycompass.eu/app/#!/visualizations/create/?datasets=59), i was executing $scope.individualCombo_value_[59]=[] in the console while the code was stopped on my brakepoint) which i can't think why it could happen randomly on firefox.

@mmilaprat your scoping is all other the place and you should consider braking the code in separate feature files. Also try limiting the server requests for the same data (the attached screenshot is from a single page load, requesting 6 times the same dataset).
![image](https://cloud.githubusercontent.com/assets/1640100/13578360/cea3a78c-e497-11e5-84c0-d4f223f7b83b.png)

**Comment by mmilaprat** [comment]
I think that I solve tre problem disabling the "ad dataset" button until the data is loaded.

I upload code in this  PR policycompass/policycompass-frontend/pull/315

In this PR I also solve the problem reported by @th0br0 when you unlink and cancel.

**Comment by cbotsikas** [comment]
Also note that i tried to brake the code in different ways, including manipulating server responses (delay, timeout, 404) and i failed to reproduce the issue. It was either braking the visualisation altogether or it was working fine. In my tests, whenever the visualisation was visible (aka, the loading indicator was hidden) i could also see the individuals in the modal popup (except the above method with the brakepoint) .

**Comment by cbotsikas** [comment]
@mmilaprat "I think that I solve tre problem disabling the "add dataset" button until the data is loaded." 
I was able to click the button before the server responded (delaying the server responses for the data requests) but the modal would always show only after the data would arrive (when the loading spinner is hidden and the visualisation would draw)

**Comment by cbotsikas** [comment]
I've finally figured out how to reproduce the issue but this requires network manipulation. As i said earlier, there are 6 requests for the same dataset. i've figured that if i delay one of them (a specific one) until the rest have finished, the individuals will disappear. I'll try to investigate more and let you know.

**Comment by cbotsikas** [comment]
Ok, i've found the bug.

TL;TR
If [block 1247-1274](https://github.com/policycompass/policycompass-frontend/blob/ddda7deefc19abf8064446403f6ad9701443feda/app/modules/visualization/controllers/visualizationControllers.js#L1247-L1274) executes after [block 145-255](https://github.com/policycompass/policycompass-frontend/blob/ddda7deefc19abf8064446403f6ad9701443feda/app/modules/visualization/controllers/visualizationControllers.js#L145-L255), the individuals disappear from the modal popup because both clear $scope.individualCombo_value_ array which is properly populated on the second block at [line 192](https://github.com/policycompass/policycompass-frontend/blob/ddda7deefc19abf8064446403f6ad9701443feda/app/modules/visualization/controllers/visualizationControllers.js#L192), [line 1261](https://github.com/policycompass/policycompass-frontend/blob/ddda7deefc19abf8064446403f6ad9701443feda/app/modules/visualization/controllers/visualizationControllers.js#L1261) seems to be the one causing the issue.

--

In [line 1261](https://github.com/policycompass/policycompass-frontend/blob/ddda7deefc19abf8064446403f6ad9701443feda/app/modules/visualization/controllers/visualizationControllers.js#L1261), $scope.individualCombo_value_  gets cleared (part of VisualizationsControllerHelper factory used in VisualizationsEditController controller; requested dataset at [L1246](https://github.com/policycompass/policycompass-frontend/blob/ddda7deefc19abf8064446403f6ad9701443feda/app/modules/visualization/controllers/visualizationControllers.js#L1246)).
The correct data (as far as i understand your code) is populated at [line 192](https://github.com/policycompass/policycompass-frontend/blob/ddda7deefc19abf8064446403f6ad9701443feda/app/modules/visualization/controllers/visualizationControllers.js#L192) (part of LoadCombosMetric controller; based on the promised response for each individual [L170](https://github.com/policycompass/policycompass-frontend/blob/ddda7deefc19abf8064446403f6ad9701443feda/app/modules/visualization/controllers/visualizationControllers.js#L170) of the dataset requested at [L144](https://github.com/policycompass/policycompass-frontend/blob/ddda7deefc19abf8064446403f6ad9701443feda/app/modules/visualization/controllers/visualizationControllers.js#L144)). 
For my network and browsers, the first dataset request, L1246, is always requested first and processed faster than the second one, L144, but since the code is asynchronous, this is not guaranteed and apparently that's what @YuriGlickman is experiencing with Firefox (maybe there is a proxy on his network too).

I've a feeling that the correct code was intended to be used on a deprecated html part [L319](https://github.com/policycompass/policycompass-frontend/blob/842ed911bcf24aa4eb1f3c8f2ab69cf8300654d6/app/modules/visualization/partials/create.html#L319) by a hidden (and not deactivated/deleted) [Tab "Datasets" L286](https://github.com/policycompass/policycompass-frontend/blob/842ed911bcf24aa4eb1f3c8f2ab69cf8300654d6/app/modules/visualization/partials/create.html#L286) and the results of it are used on the modal window too.

--

@mmilaprat :
Probably, an easy solution is to remove [line 1261](https://github.com/policycompass/policycompass-frontend/blob/ddda7deefc19abf8064446403f6ad9701443feda/app/modules/visualization/controllers/visualizationControllers.js#L1261).

In general, prefer using ng-if instead of ng-show/ng-show. [Read here the difference](http://stackoverflow.com/a/21870119). 

Replace blocks like the one at [L88-90](https://github.com/policycompass/policycompass-frontend/blob/842ed911bcf24aa4eb1f3c8f2ab69cf8300654d6/app/modules/visualization/partials/addDataset.html#L88-L90) with ng-pluralize (like it's used in search module [L28-30](https://github.com/policycompass/policycompass-frontend/blob/master/app/modules/search/partials/browse.html#L28-L30)

Also, please delete old code, commented and not (i can see code like [ng-show="1==2"](https://github.com/policycompass/policycompass-frontend/blob/842ed911bcf24aa4eb1f3c8f2ab69cf8300654d6/app/modules/visualization/partials/create.html#L286), [if (1 == 1)](https://github.com/policycompass/policycompass-frontend/blob/842ed911bcf24aa4eb1f3c8f2ab69cf8300654d6/app/modules/visualization/controllers/visualizationControllers.js#L1100), [if (1==2)](https://github.com/policycompass/policycompass-frontend/blob/842ed911bcf24aa4eb1f3c8f2ab69cf8300654d6/app/modules/visualization/controllers/visualizationControllers.js#L1871), etc). Please note that the above mentioned deprecated html code, invokes LoadCombosMetric controller, which is needed. Refactor this code accordingly and delete what's not needed. 

I can't help any more on the bug resolution, since i find it very difficult to follow 4914 lines of code...(consider code refactoring and splitting it into separate files)

**Comment by YuriGlickman** [comment]
Cool :+1: 
it is probably the most complex investigation in the project ;)
Thank you guys and especially @cbotsikas
