### ISSUE TITLE
View my own content

### ISSUE THREAD

**Issue by nadiapo** [policycompass/policycompass#452]
As a logged in user I would like to see the content I have created in Policy Compass in a dedicated area. This content would be nice if it can be grouped per "scenario" in some way.

**Comment by mmilaprat** [comment]
@FabiApfelkern , @cbotsikas do you agree if I "clone" the search functionality adding the field "creator_path" into the search query?

**Comment by mmilaprat** [comment]
Probably is better to create a page simlar at this mock-up

![24-05-2016 18-37-25](https://cloud.githubusercontent.com/assets/6602727/15512170/d336d1e6-21de-11e6-9e19-f2d061a95f79.jpg)

**Comment by cbotsikas** [comment]
@mmilaprat I wouldn't clone. If you want i can support user (creator_path) on browse so that we can filter content with user too. If you want a different layout i could convert browse into a configurable directive so that you can use.

About the mock-up it's ok, but i think it will be a mess when the user has a lot of content... We could have a top-5 or latest-5 (based on your mock-up) for each content type or something with a "See more" button for each list that will redirect the user to browse with appropriate filters (content-type, user_path)

**Comment by mmilaprat** [comment]
My idea was that each block (My dataset, My Events, ..) will have their own pagination (this doesn't appears into the mock-up).

About the posibility to add the creation_path into the browse section, I think that it can be a good solution. 

What do you think it's better? the new "My contetn" page or add the ceator_path?

**Comment by mmilaprat** [comment]
today into the weekly telco we agreed to add a new filter into the Browse section, @cbotsikas how we can proceed? Can you add this filter?
