### ISSUE TITLE
Sorting by Date Created in Browse not correct

### ISSUE THREAD

**Issue by FabiApfelkern** [policycompass/policycompass#673]
If you choose to sort by date in browse it seems not to work correctly. https://policycompass.eu/app/#!/browse?sort=Date Somehow it is still sorted by entity type.

**Comment by cbotsikas** [comment]
we need to have common property names for dates in order to sort all entities. 
At the moment the first implementation is using ids to sort them out (the bigger the id, the latest creation date) but since the ids are separate between the different entities, it's not working as expected at the beginning of the project (on stage the ids for FCMs is ~190 vs datasets ~50). This is the reason the results appear to be sorted by both the entity type and the date.

**Comment by fabiankirstein** [comment]
@cbotsikas Is this entirely done?
