### ISSUE TITLE
The formula input field is gone

### ISSUE THREAD

**Issue by fabiankirstein** [policycompass/policycompass#689]
I cannot create a metric, because the formula input is gone.

**Comment by cbotsikas** [comment]
@FabiApfelkern you are probably using Firefox. In Chrome it's fine. 
The problem is that the editable area has 0px height on firefox when there are no contents.
A quick fix is to add "min-height: 2em;" at the [text-formula class](https://github.com/policycompass/policycompass-frontend/blob/9739460e0ad16e952815640ab4b7dd1783cbe56e/app/sass/components/_pages-formula.scss#L34)

**Comment by slomo** [comment]
Fixed in https://github.com/policycompass/policycompass-frontend/pull/553
